name: Dispatch for master

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Run a one-line script
      run: |
        curl -vs --request POST \
        --url https://api.github.com/repos/slaystack/xops/dispatches \
        --header "authorization: token ${PA_TOKEN}" \
        --header 'Accept: application/vnd.github.everest-preview+json' \
        --header 'content-type: application/json' \
        --data '{
          "event_type": "ops_update",
          "client_payload": {
            "app" : "demo",
            "dependency" : "demo",
            "repo" : "${{ github.repository }}",
            "branch" : "${{ github.ref }}",
            "commit" : "${{ github.sha }}",
            "event": "${{ github.event }}"
            }
          }'
      env:
        PA_TOKEN: ${{ secrets.PA_TOKEN }}







