name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: docker
      uses: docker://docker
      with:
        args: /bin/sh ./build.sh
      env:
        REGISTRY_ENDPOINT: registry.hub.docker.com
        REGISTRY_REPO: registry.hub.docker.com/dockerdig/hello-world
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
}:actions
      env:
        REGISTRY_ENDPOINT: registry.hub.docker.com
        REGISTRY_REPO: registry.hub.docker.com/dockerdig/hello-world
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
